# the name of Camel
camel:
  springboot:
    name: MyCamel
routes:
  routeList:
      -
        routeId: route1
        source: 
          path: file://inbox1
          camelConfig: 
            delay: 2000
            doneFileName: archive
            readLock: changed          
        destinations:
        -
          path: file://outbox1
          camelConfig: 
            delay: 1000
            doneFileName: archive
            readLock: changed
          optionalConfig:
            propKey: propValue
      -
        routeId: route2
        source: 
          path: file://inbox2
          camelConfig:
            delay: 2000
            doneFileName: archive
            readLock: changed          
        destinations:
        -
          path: file://outbox1
          camelConfig:           
          optionalConfig:
            propKey: propValue
        -
          path: file://outbox2
          optionalConfig:
            propKey: propValue        